language: elixir
sudo: false
notifications:
  email: false

elixir:w
  - 1.7

otp_release:
  - 21.1

addons:
  postgresql: "9.4"
services:
  - postgresql

cache:
  directories:
    - _build
    - deps

script:
  - make testing
after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
